---
- name: Create the non-root user
  when: not github_actions
  user:
    name: "{{ vault_vps_user }}"
    password: "{{ vault_vps_password | password_hash('sha512') }}"
    shell: "/bin/bash"

- name: Add local public key for key-based SSH authentication
  when: not github_actions
  authorized_key:
    user: "{{ vault_vps_user }}"
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_hugin_cache.pub

- name: Restrict root SSH logins
  when: not github_actions
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Restrict SSH logins to keys only
  when: not github_actions
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Restart sshd
  when: not github_actions
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

