---
#- name: Ensure necessary packages are installed
#  apt:
#    name: "{{ base_pkgs }}"
#    state: present
#    update_cache: yes

- name: Create the non-root user
  user:
    name: "{{ vault_vps_user }}"
    password: "{{ vault_vps_password | password_hash('sha512') }}"
    shell: "/bin/bash"
  when: github_actions == false

- name: Add local public key for key-based SSH authentication
  authorized_key:
    user: "{{ vault_vps_user }}"
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_hugin_cache.pub
  when: github_actions == false

- name: Restrict root SSH logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'
  when: github_actions == false

- name: Restrict SSH logins to keys only
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'
  when: github_actions == false

- name: Restart sshd
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd
  when: github_actions == false

