---
- hosts: vps
  remote_user: root
  become: true
  gather_facts: no
  vars:
    hugin_cache_name: hugin_cache
    hugin_cache_port: 3000

    # A list of users who will be added to the docker group.
    docker_users: [
      "hugin_docker"
    ]

    # Docker daemon options as a dict
    docker_daemon_options: { }

    # Docker GitHub Container Registry
    docker_image: "ghcr.io/kryptokrona/hugin-cache:latest"
  roles:
    - base
    - docker
    - nginx
    - postgres