name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues and NEW pull requests to Kryptokrona project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/orgs/kryptokrona/projects/8'

      - name: Assign issues and pull requests with `bug` and `feature` label to Kryptokrona project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          contains(github.event.issue.labels.*.name, 'bug') ||
          contains(github.event.pull_request.labels.*.name, 'bug') ||
          contains(github.event.issue.labels.*.name, 'feature') ||
          contains(github.event.pull_request.labels.*.name, 'feature')
        with:
          project: 'https://github.com/orgs/kryptokrona/projects/8'
          column_name: 'Labeled'