name: Hugin Cache Load Testing

on: push
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: hugin_cache_prod
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      hugin-cache:
        image: ghcr.io/kryptokrona/hugin-cache:latest
        ports:
           - 3000:3000
    
    env:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:test1234@0.0.0.0:5432/hugin_cache_prod

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: Log into registry ghcr.io
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_PAT }}

      - name: Run Local k6 Test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/k6/loadTest.js
      
      - name: Upload Performance Test Results
        uses: actions/upload-artifact@v3
        with:
          name: hugin-cache-k6-report
          path: summary.json