name: Hugin Cache Load Testing

on: push
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: hugin_cache_prod
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:test1234@0.0.0.0:5432/hugin_cache_prod

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      
      - name: Install Packages
        run: |
          npm install
      
      - name: Start Server and Run Tests
        run: |
          npm start & npx wait-on http://localhost:3000
          ./k6 run tests/k6/loadTest.js
      
      # - name: Upload Performance Test Results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: hugin-cache-k6-report
      #     path: summary.json