name: Hugin Cache Load Testing

on: push
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Start Hugin Cache
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Info
        id: info
        shell: bash
        run: |
          export CID=$(cat $CID_FILE)
          export ADDR=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CID)
          echo "::set-output name=cid::$CID"
          echo "::set-output name=address::$ADDR"

      - name: Run Local k6 Test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/k6/loadTest.js
      
      - name: Upload Performance Test Results
        uses: actions/upload-artifact@v3
        with:
          name: hugin-cache-k6-report
          path: summary.json
      
      - name: Stop Hugin Cache
        run: docker-compose -f docker-compose.test.yml down