
name: Hugin Cache Main Pipeline

on: 
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        yarn install

    - name: Unit Test
      run: |
        yarn test 
      env:
        CI: true

    # Code Coverage
      
    - name: Build
      run: |
        yarn run build --if-present

    # Build Docker Image

    # Publish Docker Image

    # Deploy