
name: Hugin Cache Main Pipeline

on: 
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log into registry ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install

    - name: Unit Test
      run: |
        npm run test 
      env:
        CI: true

    # Code Coverage
      
    - name: Build
      run: |
        npm run build --if-present

    # Build Docker Image
    - name: Build Docker
      run: docker build . --file Dockerfile --tag hugin-cache:${GITHUB_SHA::6}

    - name: Publish Docker
      run: |
        docker push hugin-cache:${GITHUB_SHA::6}
        docker push hugin-cache:latest

    # Deploy