
name: Hugin Cache Main Pipeline

env:
  GITHUB_REGISTRY: 'ghcr.io'
  GITHUB_DOCKER_IMAGE: 'hugin-cache'
  GITHUB_DOCKER_TAG: ${GITHUB_SHA::6}

on: 
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log into registry ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install

    - name: Unit Test
      run: |
        npm run test 
      env:
        CI: true

    # Code Coverage
      
    - name: Build
      run: |
        npm run build --if-present

    - name: Build Docker
      run: docker build -t $GITHUB_DOCKER_IMAGE:$GITHUB_DOCKER_TAG .

    - name: Publish Docker
      run: |
        docker push $GITHUB_REGISTRY/$GITHUB_DOCKER_IMAGE:$GITHUB_DOCKER_TAG
        docker push $GITHUB_REGISTRY/$GITHUB_DOCKER_IMAGE:latest

    # Deploy