
name: Hugin Cache Main Pipeline

env:
  githubRegistry: 'ghcr.io'
  githubDockerImage: 'hugin-cache'
  githubDockerTag: ${GITHUB_SHA::6}

on: 
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log into registry ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install

    - name: Unit Test
      run: |
        npm run test 
      env:
        CI: true

    # Code Coverage
      
    - name: Build
      run: |
        npm run build --if-present

    - name: Build Docker
      run: docker build . --file Dockerfile --tag ${{env.githubRegistry}}/${{env.githubDockerImage}}:${{env.githubDockerTag}}

    - name: Publish Docker
      run: |
        docker push ${{env.githubRegistry}}/${{env.githubDockerImage}}:${{env.githubDockerTag}}
        docker push ${{env.githubRegistry}}/${{env.githubDockerImage}}:latest

    # Deploy