name: Hugin Cache Pull Request Pipeline

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Unit Test
        run: |
          npm run test
        env:
          CI: true

      # Code Coverage

      - name: Build
        run: |
          npm run build --if-present