
name: Hugin Cache Pull Request Pipeline

on: [pull_request] 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test job (not finished)
      run: echo Hello, world!